---
# Ansible role to install Oracle Java 8
# Playbook should be runned with "--exta-vars" flag to mention the {{ app-name }}

- name: "Check If java is already installed or not"
  shell: "{{ java_name }}/bin/java -version 2>&1 | grep version | awk '{print $3}' | sed 's/\"//g'"
  register: java_installed
  tag: java
  
- name: "Installed java version"
  debug: 
    msg: "{{ java_installed.stdout }}"
  tag: java

- name: "Download Java"
  get_url:
    url: "{{ download_url }}"
    dest: "{{ java_archive }}"
    headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie; --no-check-certificate'     
  tag: java

- name: Unarchive Java
  unarchive:
    src: "{{ java_archive }}"
    dest: "{{ download_folder }}"
    remote_src: yes
  tag: java

- name: Fix ownership
  file: 
    state: directory 
    path: "{{ java_name }}" 
    owner: root 
    group: root 
    recurse: yes
  tag: java

- name: Download the JCE policy for oracle-jdk8
  get_url: 
    url: "{{ jce_download_url }}"
    dest: "{{ jce_archive }}"
  tag: java
    
- name: install oracle java policy software (JCE)
  unarchive:
    src: "{{ jce_archive }}"
    dest: "{{ download_folder }}"
  tag: java

- name: Install java aletrnatives
  command: 'alternatives --install "/usr/bin/java" "java" "{{ java_name }}/bin/java" 2000'
  tag: java

- name: Set/Configure JAVA_HOME in environment variables 
  shell: "echo 'export JAVA_HOME={{ java_name }}\n export PATH=$JAVA_HOME/bin:$PATH' > {{ java_env_file }}"
  tag: java